### ISSUE TITLE
Session secret hard coded. Should probably put this in an env.

### ISSUE THREAD

**Issue by RobLMartin** [creativeplatform/creative-tv#8]
https://github.com/creativeplatform/creative-tv/blob/f236044b17cfd8054eea53259ddab28492d3ac27/src/pages/api/siwe/siwe.ts#L5

https://martinfowler.com/articles/session-secret.html

**Comment by sirgawain0x** [comment]
@starhelios  would you mind helping us with this fix, please. Thanks @RobLMartin 👍🏾

**Comment by starhelios** [comment]
> @starhelios would you mind helping us with this fix, please. Thanks @RobLMartin 👍🏾

Okay, I will fix this soon.
